apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 8300
    protocol: TCP
    targetPort: 80
    nodePort: 31665
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}