---
- name: Applying custom tasks on EC2 instance
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  roles:
  - ./roles/master-nodes
  tags: master-nodes

  - ./roles/worker-nodes
  tags: worker-nodes
 