---
- name: Installing K8S cluster
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  roles:
  - ./roles/master-nodes
  tags: master-nodes

- name: Installing worker nodes
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  roles:
  - ./roles/worker-nodes
  tags: worker-nodes

- name: Deploying nginx
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  # roles:
  # - ./roles/deploy-app
  # tags: nginx-deploy


